language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: tylerwmarrs
  password:
    secure: LrIrKVHiUURPn6gSB959fpUA7s/Hj5ksAeuB3Rolx0jXUQc6JcrNXbvbGHaLZg7oO1o+sr60/lVmYFzifxzZIykjyq0j85zMepknbaNWnmHFpamJbCsXC9qzwXhdsLRjUwwqRfK/TVDeDo5DehD2FAT4fnolre4Rm9jALL3fQR44Icp+44f3JMAV2wmAeRagXol0V2IHXZTf4DPJXdkvlEDFwUxYqhna+TJL4mcyYprvhddrkXEw+HSBt81Z2vXr+WmLHCYnykmDbpHrC8yPM+/bGHJnJLqomyP7zRfkFmjMUENiPpVmzfA8QzhXqHki/2HVKmmzaYnD9jN2MKWStAY8ptwlpUQIpVGOFmNumMWuJU9Z0JUihq92u7UfOYdyECeB/dS7/mFYCn+Z4QuXIUWumfN5Dmvrxs0bep4ynPtuWWxmybxo1TQSD9zMbZ/Bvi0u9FJ/OtXdxhKPRNP5nZ7KST2P3FwN0ey7LuWr6tCF2hoUKpenLLRuk258nAGWikjawmorKQJpniFl5jwUzBS7TusNpdobehHbBjmvOI/Nn6WWwC12/uN9+pJANVwaatTEfdI6LvSKWySA0wEITHd21EsuIIN2qbhmezINF8M/muKi5Zz+WhXIUDo80KOk8yp8MIy4FHONcXW/5mboNeSfzMJ6lKQ9ysBZdrx2ZMA=
  on:
    tags: true
    repo: tylerwmarrs/mass-ts
    python: 3.6
